export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const NOTIFICATION_WARNING = 'NOTIFICATION_WARNING';
export const NOTIFICATION_INFO = 'NOTIFICATION_INFO';
export const NOTIFICATION_SUCCESS = 'OTIFICATION_SUCCESS';
